# Status bar colors
set-option -g status-style bg=colour236,fg=colour250

# Session name (left side) in Dracula green
set-option -g status-left '#[fg=colour10,bold] #S #[default]'

# Right: hostname, time, date (same as before)
set-option -g status-right '#[fg=colour81] #(hostname -s) | %H:%M #[fg=colour81]%d-%b-%y#[default]'

# Always passthrough the copy/paste
set -g allow-passthrough on

# Active tab (current window) in Dracula pink
set-window-option -g window-status-current-format '#[fg=colour213,bold] #I:#W #[default]'

# Inactive tabs in light gray
set-window-option -g window-status-format '#[fg=colour250] #I:#W #[default]'

# Show only the current folder name in the window/tab title
set-option -g status-interval 1
set-option -g automatic-rename on
set-option -g automatic-rename-format '#{b:pane_current_path}'

set -g mouse on

set-option -g prefix2 `
bind-key ] next-window
bind-key [ previous-window
bind-key l choose-window

bind-key h display-popup -E -w 80% -h 80% "htop"
bind-key r command-prompt -I "#W" "rename-window '%%'"

# Split panes using v and h (after prefix)
bind v split-window -h
bind h split-window -v

# Move windows +/-1
bind-key n swap-window -t +1 \; next-window
bind-key p swap-window -t -1 \; previous-window

# Search in command history
bind-key C-f display-popup -w 80% -h 80% -E "bash -c '
selected=\$(tac ~/.bash_history \
  | awk \"!seen[\\\$0]++\" \
  | fzf --tac \
  | awk \"{\$1=\\\"\\\"; sub(/^ /,\\\"\\\"); print}\"
);
[ -n \"\$selected\" ] && tmux set-buffer \"\$selected\" && tmux paste-buffer -t \"#{pane_id}\"
'"

# Great for remote copy it allows to do this:
# copy text to clipboard
# printf '\033]52;c;%s\a' "$(echo -n '{{TEXT}}' | base64)"
# copy file content to clipboard
# printf '\033]52;c;%s\a' "$(base64 -w 0 {{FILE}})"
set -g allow-passthrough on
set -g set-clipboard on
