# Status bar colors
set-option -g status-style bg=colour236,fg=colour250

# Session name (left side) in Dracula green
set-option -g status-left '#[fg=colour10,bold] #S #[default]'

# Right: hostname, time, date (same as before)
set-option -g status-right '#[fg=colour81] #(hostname -s) | %H:%M #[fg=colour81]%d-%b-%y#[default]'

# Active tab (current window) in Dracula pink
set-window-option -g window-status-current-format '#[fg=colour213,bold] #I:#W #[default]'

# Inactive tabs in light gray
set-window-option -g window-status-format '#[fg=colour250] #I:#W #[default]'

set-option -g prefix2 `
bind-key ] next-window
bind-key [ previous-window
bind-key l choose-window
bind-key h display-popup -E -w 80% -h 80% -x 10 -y 5 "htop"

set -g mouse on

